// Generated by BUCKLESCRIPT VERSION 1.5.3+dev, PLEASE EDIT WITH CARE
'use strict';

var Curry      = require("bs-platform/lib/js/curry");
var Pervasives = require("bs-platform/lib/js/pervasives");

function map(f, param) {
  if (param) {
    return /* Some */[Curry._1(f, param[0])];
  }
  else {
    return /* None */0;
  }
}

var a = { };

var b = {
  foo: "42"
};

function make(foo) {
  var partial_arg = map(Pervasives.string_of_int, foo);
  return function () {
    return {
            foo: partial_arg ? partial_arg[0] : undefined
          };
  };
}

var a$prime = make(/* None */0)(/* () */0);

var b$prime = make(/* Some */[42])(/* () */0);

exports.map     = map;
exports.a       = a;
exports.b       = b;
exports.make    = make;
exports.a$prime = a$prime;
exports.b$prime = b$prime;
/* a' Not a pure module */
